name: Release

on:
    release:
        types: [published]

env:
    SSC_BRANCH: 'playmint-next'

permissions:
    contents: write

jobs:
    mac_build:
        name: macOS build
        runs-on: macOS-14
        needs: [create_release]
        timeout-minutes: 30

        steps:
            - name: checkout socket
              uses: actions/checkout@v3
              with:
                  repository: 'playmint/socket'
                  ref: '${{ env.SSC_BRANCH }}'
                  path: 'socket'
            - name: install node
              uses: actions/setup-node@v3.6.0
              with:
                  node-version: 20.x
            - name: cache socket build
              id: cache-ssc
              uses: actions/cache@v3
              env:
                  cache-name: cache-ssc
              with:
                  path: './socket/build'
                  key: ${{ runner.os }}-ssc-${{ hashFiles('socket/.git/refs/heads/${{ env.SSC_BRANCH }}') }}
                  restore-keys: |
                      ${{ runner.os }}-ssc-${{ env.cache-name }}-
                      ${{ runner.os }}-ssc-
                      ${{ runner.os }}-

            - name: install deps
              run: |
                  brew install automake pnpm libtool
            - name: build ssc
              working-directory: './socket'
              run: |
                  VERBOSE=1 ./bin/install.sh
                  ./bin/ci_version_check.sh
              env:
                  VERBOSE: '1'
                  NO_ANDROID: '1'
                  NO_IOS: '1'
                  CI: 'true'
                  SSC_ANDROID_CI: 'false'
            - name: checkout app
              uses: actions/checkout@v3
              with:
                  ref: '${{ github.event.release.target_commitish }}'
                  path: './app'
            - name: build app
              working-directory: './app'
              run: |
                  ssc --version
                  pnpm install
                  pnpm run build
                  ls build/**/*
            - name: Upload Release Asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: '${{ github.event.release.upload_url }}'
                  asset_path: './app/build/mac/substream.zip'
                  asset_name: 'substream-macos-arm64.zip'
                  asset_content_type: 'application/zip'
